## Put comments here that give an overall description of what your
## functions do

## The function is a helper to the cachSolve
# function. It returns a list of 4 functions
# that are used by cacheSolve. These four
# functions are getter and setter methods
# for inverse and the matrix itself.


makeCacheMatrix <- function(x = matrix()) 
{
    temp <- NULL
    set <- function(val) {
        x <<- val
        temp <<- NULL
    }
    get <- function() x
    setInverse <- function(inverse) temp <<- inverse
    getInverse <- function() temp
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## It calculates the inverse of a matrix with the
# help of helper functions generated by mackCacheMatrix
# given above. If the inverse has been cached,
# then the cached copy is invoked, else inverse 
# value is calculated with the help of solve
# function and then added to the cached items.
cacheSolve <- function(x, ...) 
{
    ## Returns a matrix that is the inverse of 'x'
    inv <- x$getInverse()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setInverse(inv)
    inv
}
